# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a53b75e0bce8c089ad3aae620c286edfa8ac6697889c13227dff666c3b5c2d57e2b4f0e2c94ce7a5dc635ab491d63b554a7f6d77ed7e63e52626ac6c37ca8def

test:
  secret_key_base: bac21df54fad64fcf65d8a6a1b6a4b40cb1f29c30048c91059bc409d3d926d07726016580c31bd8e01805901586058ff72bce5dcd6ce120277dc9634fe3a4bd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
